In [1]:
import numpy as np
import re

### Задача 1

In [2]:
date_string = '''totwrk                       -0.169***         
                              (0.018)          
                                               
age                           2.689*           
                              (1.469)          
                                               
south                        101.568**         
                             (41.837)          
                                               
male                         87.669**          
                             (35.104)          
                                               
smsa                         -54.748*          
                             (33.123)          
                                               
yngkid                        -13.962          
                             (50.341)          
                                               
marr                          31.211           
                             (42.233)          
                                               
Constant                    3450.913***        
                             (80.726)'''

In [3]:
digital_date = re.findall(r'([-+]?\d+.\d+)',date_string)
digital_date

['-0.169',
 '0.018',
 '2.689',
 '1.469',
 '101.568',
 '41.837',
 '87.669',
 '35.104',
 '-54.748',
 '33.123',
 '-13.962',
 '50.341',
 '31.211',
 '42.233',
 '3450.913',
 '80.726']

In [4]:
beta = np.reshape(digital_date,(8,2))
beta

array([['-0.169', '0.018'],
       ['2.689', '1.469'],
       ['101.568', '41.837'],
       ['87.669', '35.104'],
       ['-54.748', '33.123'],
       ['-13.962', '50.341'],
       ['31.211', '42.233'],
       ['3450.913', '80.726']], dtype='<U8')

In [5]:
beta = beta.astype(float)
beta

array([[-1.690000e-01,  1.800000e-02],
       [ 2.689000e+00,  1.469000e+00],
       [ 1.015680e+02,  4.183700e+01],
       [ 8.766900e+01,  3.510400e+01],
       [-5.474800e+01,  3.312300e+01],
       [-1.396200e+01,  5.034100e+01],
       [ 3.121100e+01,  4.223300e+01],
       [ 3.450913e+03,  8.072600e+01]])

In [7]:
beta[:,0]

array([-1.690000e-01,  2.689000e+00,  1.015680e+02,  8.766900e+01,
       -5.474800e+01, -1.396200e+01,  3.121100e+01,  3.450913e+03])

In [8]:
ppl_string = '''totwrk age south male smsa yngkid marr
----------------------------------------
1  2150  37    0    1    1     0     1  
2  1950  28    1    1    0     1     0  
3  2240  26    0    0    1     0     0 '''

In [9]:
ppl_lst = re.findall(r'([-+]?\d+)', ppl_string)
ppl_lst

['1',
 '2150',
 '37',
 '0',
 '1',
 '1',
 '0',
 '1',
 '2',
 '1950',
 '28',
 '1',
 '1',
 '0',
 '1',
 '0',
 '3',
 '2240',
 '26',
 '0',
 '0',
 '1',
 '0',
 '0']

In [12]:
ppl_numb = np.reshape(ppl_lst,(3,8))
ppl_numb 

array([['1', '2150', '37', '0', '1', '1', '0', '1'],
       ['2', '1950', '28', '1', '1', '0', '1', '0'],
       ['3', '2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [13]:
ppl_numb = np.delete(ppl_numb,0,1)
ppl_numb

array([['2150', '37', '0', '1', '1', '0', '1'],
       ['1950', '28', '1', '1', '0', '1', '0'],
       ['2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [14]:
ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([['2150', '37', '0', '1', '1', '0', '1', '1.0'],
       ['1950', '28', '1', '1', '0', '1', '0', '1.0'],
       ['2240', '26', '0', '0', '1', '0', '0', '1.0']], dtype='<U32')

In [15]:
beta = beta.astype(float)
ppl_numb=ppl_numb.astype(float)

In [16]:
beta

array([[-1.690000e-01,  1.800000e-02],
       [ 2.689000e+00,  1.469000e+00],
       [ 1.015680e+02,  4.183700e+01],
       [ 8.766900e+01,  3.510400e+01],
       [-5.474800e+01,  3.312300e+01],
       [-1.396200e+01,  5.034100e+01],
       [ 3.121100e+01,  4.223300e+01],
       [ 3.450913e+03,  8.072600e+01]])

In [17]:
ppl_numb

array([[2.15e+03, 3.70e+01, 0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00,
        1.00e+00, 1.00e+00],
       [1.95e+03, 2.80e+01, 1.00e+00, 1.00e+00, 0.00e+00, 1.00e+00,
        0.00e+00, 1.00e+00],
       [2.24e+03, 2.60e+01, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
        0.00e+00, 1.00e+00]])

In [18]:
ppl_numb@beta[:,0]

array([3251.188, 3371.93 , 3087.519])

In [19]:
beta[0,1]

0.018